_target_: models.hiero.HiERO

# Hidden size used in the temporal convolution layers
hidden_size: 768

# Number of conv1d layers at each depth
n_layers: 3

# Local temporal connectivity at each layer
k: 1.0

# Number of temporal convolution layers
depth: 3

# Projection type (possibly none)
input_projection: True

# Dropout
dropout: 0.1

defaults:
  - conv: TDGC

conv:
  in_channels: ${model.hidden_size}
  out_channels: ${model.hidden_size}

# pooling strategy
pool: mean # max or mean

# HiERO clustering parameters
n_clusters: 4
clustering_sample_points: 32
clustering_at_inference: False