_target_: models.tasks.hiero.HiEROTask

input_size: ${model.hidden_size}
features_size: 768

dropout: 0

loss_weight: 1.0
proc_loss_weight: 1.0

temperature: 0.05

# Finetune the text encoder using LoRa
text_encoder: distillbert # or clip (the first for egovlp features,)
# Pre-trained weights for the text encoder
text_encoder_weights: pretrained/egovlp_text.pth
# LoRa finetuning of the text encoder
text_encoder_full_ft: False

# Contrastive mode (video to text, text to video or symmetric)
contrastive_mode: sym  # 'v2t', 't2v', 'sym'

# alpha coefficient controls the width of the contrastive window for positive samples
alpha: 1.0

# beta coefficient controls the width of the contrastive window for intra-video negative samples
# -1.0 is a special value that means that all the samples from the same video as negatives
beta: -1.0
