# Default configuration file for all experiments

device: cuda
seed: 1234567891

# Default hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d-%H-%M-%S}

# Resume and save paths
resume_from: null
save_to: null

train_dataset:
  _target_: data.egoclip.EgoClipDataset
  root: data/ego4d

val_dataset:
  _target_: data.egomcq.EgoMCQDataset
  root: ${train_dataset.root}
  context_window_size: 4


##########################
# Training configuration #
##########################

batch_size: 8
num_workers: 1
persistent_workers: True
num_epochs: 15
steps_per_round: 1000

# LR scheduler configuration
lr_warmup: True
lr_warmup_epochs: 5
# Minimum learning rate
lr_min: 1e-8

# Optimizer parameters
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5
  weight_decay: 1e-5

gradient_clip: 1.0
save_model: False

defaults:
  - model: hiero
  - task: hiero
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog